### PR TITLE
Add protocol property to Device model

### PR DESCRIPTION
**Pull request by tetienne**

### CODE REVIEW

**Comment by tetienne** [comment]
I don’t get why I haven’t this duplicate code error locally :o

**Comment by iMicknl** [comment]
> I don’t get why I haven’t this duplicate code error locally :o

Because you don't run Python 3.8? However I have seen this error before, but I don't recall where.

image

**Comment by tetienne** [comment]
I ran the `tox` command too on my machine, and also `poetry run pre-commit run -a`. You can reproduce?

**Comment by tetienne** [comment]
@iMicknl Fixed :D

**Review by vlebourl — APPROVED** [review]

**Review by iMicknl — CHANGES_REQUESTED** [review]
https://github.com/iMicknl/python-overkiz-api/blob/main/pyoverkiz/enums/__init__.py

Could you perhaps add this one to init as well? Most of the enums we just import from `pyoverkiz.enums`.

**Comment by tetienne** [comment]
> https://github.com/iMicknl/python-overkiz-api/blob/main/pyoverkiz/enums/__init__.py
> 
> Could you perhaps add this one to init as well? Most of the enums we just import from `pyoverkiz.enums`.

Done

**Review by iMicknl — APPROVED** [review]

**Pull request merged**
