### PR TITLE
New API Manager URL & Client ID for Atlantic

### PR DESCRIPTION
**Pull request by adetante**
Fix issue #681

### CODE REVIEW

**Comment by iMicknl** [comment]
@adetante can you elaborate on where you found the new credentials / API? Did you take this from the Android app?

We need to double check if this does not break other accounts, but I hope to merge it tomorrow, if I am able to test.

**Comment by adetante** [comment]
Hi @iMicknl
Yes, from the latest version of the Android app (3.6.0) I got the following values from `BuildConfig`:

```
public static final PROD_END_POINT = "/magellan"
public static final PROD_END_POINT_OLD = "/gacoma/gacomawcfservice"
public static final PROD_URL = "https://apis.groupe-atlantic.com"
public static final PROD_URL_OLD = "https://api.groupe-atlantic.com"
```

I use this python lib to get cozy touch data in my home assistant dashboard, and the API calls do not work anymore with the old URL.

For the credentials, unfortunately I can't inspect the calls made by the Android app at the moment.
I got the value from this PR: https://github.com/geogeocutcut/jeedom-cozytouch-plugin/pull/14/files

And indeed in my local installation these new credentials work.
But I can't guarantee that it's the one currently used by the Android app...

**Comment by iMicknl** [comment]
Thanks @adetante! I will have a look :).

**Comment by iMicknl** [comment]
@adetante I was able to verify this with 2 users and it seems to work.

Thanks for your contribution!

**Review by iMicknl — APPROVED** [review]

**Pull request merged**
