### PR TITLE
Skip None value, fixes retrieval of diagnostics

### PR DESCRIPTION
**Pull request by jwillemsen**
Fixes diagnostics retrieval issue as part of https://github.com/home-assistant/core/issues/111818

### CODE REVIEW

**Comment by iMicknl** [comment]
Would it be possible to add your setup.json to the repo as well and add this to our test suite?

Regarding the linting issue, fine by me to disable this rule via a comment in your code.

**Comment by jwillemsen** [comment]
Ok, disabled the rule, added my json to the fixtures/setup directory, is that the correct place?

**Comment by iMicknl** [comment]
Apparently we don't have a test yet for the obfuscate feature; but good to add your fixture nevertheless.

**Review by iMicknl — APPROVED** [review]

**Comment by jwillemsen** [comment]
For the obfuscate feature, the problem is I think this list in the raw data `'cooling': {'d': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None, None, None]`

**Comment by jwillemsen** [comment]
> Apparently we don't have a test yet for the obfuscate feature; but good to add your fixture nevertheless.

And added a test case for this, without my patch the test fails with

```
=============================================================================================================================================================================== FAILURES ================================================================================================================================================================================
_________________________________________________________________________________________________________________________________________________________ TestObfucscateSensitive.test_obfuscate_sensitive_data _________________________________________________________________________________________________________________________________________________________

self = <tests.test_obfuscate.TestObfucscateSensitive object at 0x7f404f5bfa10>

    def test_obfuscate_sensitive_data(self):
        input = {'d': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None, None, None]}
>       assert obfuscate_sensitive_data(input) == input

tests/test_obfuscate.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pyoverkiz/obfuscate.py:73: in obfuscate_sensitive_data
    obfuscate_sensitive_data(val)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

data = None

    def obfuscate_sensitive_data(data: dict[str, Any]) -> JSON:
        """Mask Overkiz JSON data to remove sensitive data"""
        mask_next_value = False
    
>       for key, value in data.items():
E       AttributeError: 'NoneType' object has no attribute 'items'

pyoverkiz/obfuscate.py:31: AttributeError
```

**Pull request merged**
