### PR TITLE
Add method to execute scheduled scenario

### PR DESCRIPTION
**Pull request by PingouInfini**
Add new method and new associated event name

### CODE REVIEW

**Review by tetienne — APPROVED** [review]
Thank you for your contribution!

**Comment by iMicknl** [comment]
@PingouInfini could you run the pre-commits hooks / black? Or did you do this and is this an issue in the CI/CD here.

**Comment by PingouInfini** [comment]
My bad. 
I was stuck with this mypy hook issue "pyoverkiz/client.py:316: error: Returning Any from function declared to return "str"" so I bypassed it.
New commit with fixes for hooks compliance
And I don't know why the CI/Python 8 is in error.

**Comment by iMicknl** [comment]
```
  mypy.....................................................................Failed
  - hook id: mypy
  - exit code: 1
  
  pyoverkiz/client.py:316: error: Redundant cast to "str"  [redundant-cast]
```

I will have a look if I can fix it for you soon :-).

**Comment by PingouInfini** [comment]
@iMicknl Everything seems fine with these latest commits.

**Pull request merged**
